### ISSUE TITLE
Missing property after updating

### ISSUE THREAD

**Issue by adazem009** [yeti0904/noro#4]
After updating noro to v0.2.1, I'm getting the following error message:
`[ERROR] missing property in config file: ruler`
A workaround for this is to remove `~/.config/noro/settings.ini`.

Suggested solution:
When a required property does not exist, do not exit with an error message and instead add the missing property with its default value.

**Comment by yeti0904** [comment]
i will add your suggested solution in the next update

**Comment by yeti0904** [comment]
fixed in 03f8d28945a2ee4cc5fe74a7e1269f064f15ecf7
